-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Aug 04, 2016 at 04:12 AM
-- Server version: 5.6.17
-- PHP Version: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `shoedb`
--

-- --------------------------------------------------------

--
-- Table structure for table `cart_details`
--

CREATE TABLE IF NOT EXISTS `cart_details` (
  `order_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_size` varchar(255) NOT NULL,
  `product_colors` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `dateadded` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=41 ;

--
-- Dumping data for table `cart_details`
--

INSERT INTO `cart_details` (`order_id`, `username`, `product_id`, `product_size`, `product_colors`, `quantity`, `dateadded`) VALUES
(37, '', 1, 'US 9 / UK 10 / EU 43', ' Yellow', 3, '2016-08-04 02:04:10'),
(40, 'admin', 73, 'US 9 / UK 10 / EU 43', 'dahuiwda', 4, '2016-08-04 02:11:09');

-- --------------------------------------------------------

--
-- Table structure for table `customerenquiry`
--

CREATE TABLE IF NOT EXISTS `customerenquiry` (
  `customerName` varchar(255) NOT NULL,
  `enquirySubject` varchar(255) NOT NULL,
  `customerEmail` varchar(255) NOT NULL,
  `customerEnquiry` text NOT NULL,
  PRIMARY KEY (`customerName`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `customerenquiry`
--

INSERT INTO `customerenquiry` (`customerName`, `enquirySubject`, `customerEmail`, `customerEnquiry`) VALUES
('asdf', 'Enquiry on shoes', 'asdf@gmail.com', 'asdfLorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, '),
('dwdawdw', 'wdwdadawwdwd', 'dwdawda', 'dwawdadawdaw');

-- --------------------------------------------------------

--
-- Table structure for table `order_history`
--

CREATE TABLE IF NOT EXISTS `order_history` (
  `transaction_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_size` varchar(255) NOT NULL,
  `product_colors` varchar(255) NOT NULL,
  `quantity` int(11) NOT NULL,
  `dateadded` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `billingAddress` text NOT NULL,
  `orderStatus` enum('Pending','Shipped','Delivered') NOT NULL DEFAULT 'Pending',
  `fullname` varchar(255) NOT NULL,
  `billingCity` varchar(255) NOT NULL,
  `postalCode` varchar(255) NOT NULL,
  `cardName` varchar(255) NOT NULL,
  `cardNo` int(11) NOT NULL,
  `cvvCode` int(11) NOT NULL,
  `expDate` date NOT NULL,
  PRIMARY KEY (`transaction_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=16 ;

--
-- Dumping data for table `order_history`
--

INSERT INTO `order_history` (`transaction_id`, `username`, `product_id`, `product_size`, `product_colors`, `quantity`, `dateadded`, `billingAddress`, `orderStatus`, `fullname`, `billingCity`, `postalCode`, `cardName`, `cardNo`, `cvvCode`, `expDate`) VALUES
(2, 'admin', 2, 'US 9 / UK 10 / EU 43', ' Rainbow', 4, '2016-08-01 10:30:07', '', 'Pending', '', '', '', '', 0, 0, '0000-00-00'),
(3, 'admin', 4, 'US 7 / UK 8 / EU 39', 'Black', 2, '2016-08-01 10:38:14', '', 'Shipped', '', '', '', '', 0, 0, '0000-00-00'),
(4, 'admin', 1, 'US 7 / UK 8 / EU 39', 'Blue', 2, '2016-08-01 10:46:06', 'dawawddwad', 'Delivered', '', '', '', '', 0, 0, '0000-00-00'),
(5, '1', 1, 'US 8 / UK 9 / EU 42', ' Yellow', 1, '2016-08-01 10:49:33', 'dwadaw', 'Pending', '', '', '', '', 0, 0, '0000-00-00'),
(8, 'admin', 45, 'US 9 / UK 10 / EU 43', 'Black', 3, '2016-08-02 13:14:00', 'dawawd', 'Pending', 'awdaw', 'awaw', 'waaw', 'wawdadw', 32131, 31212, '2012-12-12'),
(9, 'admin', 21, 'US 7 / UK 8 / EU 39', 'Silver', 3, '2016-08-02 13:33:41', 'aaaaaaaaaaaa', 'Pending', 'aaaaaaaaaaa', 'aaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaaaaaaa', 'aaaaaaaaaaaaa', 2147483647, 2147483647, '2016-08-10'),
(11, 'admin', 2, 'US 9 / UK 10 / EU 43', 'Orange/Green', 1, '2016-08-03 19:37:17', 'adwwwwwwwwwwwww', 'Pending', 'adwwwwwwwwwwww', 'adwwwwwwwwwwwww', 'adwwwwwwwwwwww', 'adwwwwwwwwwwww', 2147483647, 2147483647, '1111-11-11'),
(12, 'stevieg', 72, 'US 9 / UK 10 / EU 43', 'Black/Pink/Yellow', 1, '2016-08-03 22:09:15', 'Liverpool', 'Pending', 'Stevie', 'Liverpool', '123456', 'Stevie Gerrard', 123456789, 123456789, '2012-12-12'),
(13, 'whoisjunhong', 38, 'US 8 / UK 9 / EU 42', 'Black', 1, '2016-08-04 01:57:27', 'www', 'Pending', 'www', 'www', 'ww', 'www', 111, 111, '2016-08-09'),
(14, 'whoisjunhong', 2, 'US 7 / UK 8 / EU 39', 'Orange/Green', 3, '2016-08-04 02:00:07', 'awddddddddd', 'Pending', 'awdddddddddd', 'waddddddddddd', 'awdddddddddddddd', 'dawwwwwwwww', 2147483647, 2147483647, '2016-08-10'),
(15, 'qwerty', 1, 'US 9 / UK 10 / EU 43', ' Silver', 4, '2016-08-04 02:08:46', 'aaadwaaaaaaaaaaaaa', 'Pending', 'dwaaaaaaaaaaaaa', 'adwaaaaaaaaaaaaa', 'dwaaaaaaaaa', 'wdaaaaaaaaaa', 13132121, 1231312312, '2016-08-16');

-- --------------------------------------------------------

--
-- Table structure for table `product_info`
--

CREATE TABLE IF NOT EXISTS `product_info` (
  `product_id` int(11) NOT NULL AUTO_INCREMENT,
  `product_brand` varchar(255) NOT NULL,
  `product_name` varchar(255) NOT NULL,
  `product_colors` text NOT NULL,
  `product_price` double NOT NULL,
  `product_gender` enum('M','F','Y','U','B','G') NOT NULL,
  `product_category` varchar(255) NOT NULL,
  `product_subCategory` varchar(255) NOT NULL,
  `product_description` text NOT NULL,
  `product_specifications` text NOT NULL,
  `product_image` varchar(255) NOT NULL,
  `promoStatus` enum('T','F') NOT NULL,
  `newarrival` enum('T','F') NOT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=74 ;

--
-- Dumping data for table `product_info`
--

INSERT INTO `product_info` (`product_id`, `product_brand`, `product_name`, `product_colors`, `product_price`, `product_gender`, `product_category`, `product_subCategory`, `product_description`, `product_specifications`, `product_image`, `promoStatus`, `newarrival`) VALUES
(1, 'New Balance', 'NB Fresh Foam 1080 ', '"Blue", "Yellow", "Silver"', 150, 'M', 'Sports', 'Running', 'Designed using data gathered from athletes who run at an average pace, the menâ€™s Fresh Foam 1080 cushioned shoe is made for performance. In addition to supremely comfortable Fresh Foam cushioning, an engineered mesh upper gives your feet room to move while data-designed grooves on the outsole deliver the flexibility you need. Inside, the comfort continues with an OrtholiteÂ® sockliner and a bootie-like fit that feels secure on your foot. Adapt your run and make any road yours with Fresh Foam 1080.', 'Type: Cushioning\r\nWeight: 293.4 grams (10.4 oz)\r\n8 mm drop: due to variances created during the development and manufacturing processes, all references to 8 mm drop are approximate\r\nBlown rubber outsole\r\nBootie construction\r\nEngineered mesh\r\nOrtholiteÂ® foam insert delivers long term comfort, breathability, and anti-microbial function to fight odor.\r\nSynthetic/mesh upper', 'NBFreshFoam1080.jpg', 'F', 'F'),
(2, 'Nike', 'Nike Flyknit Air Max', '"Orange/Green", "Rainbow", "Oreo"', 225, 'M', 'Sports', 'Running', 'Ultralight support meets maximum cushioning in the Nike Flyknit Air Max Mens Running Shoe, featuring the most flexible Max Air unit yet and a woven one-piece Flyknit upper. The full-length Max Air unit offers the most flexibility to date while still delivering maximum cushioning for ultimate comfort on your run. Its tubular construction allows more air underfoot to encourage even transitions from heel strike through toe-off. The ultralight Flyknit upper contours to your foot for a comfortable, supportive fit. Made entirely of polyester yarn, the single-layer construction seamlessly integrates areas of high breathability, stretch and support where you need it most.', 'Weight: 12.8 ounces (Mens size 10)\r\nType: Stability\r\nUsage: Running, Casual\r\nSizes: US 6 - 14', 'NikeFlyknitAirMax.jpg', 'F', 'F'),
(3, 'Puma', 'Puma Ignite Ultimate PwrCool', '"Blue", "Lime Green"', 125, 'M', 'Sports', 'Running', '\r\nThe PUMA IGNITE is our most responsive running shoe ever, and is worn by Usain Bolt, the world''s fastest man. IGNITE features a superior cushioning material that disperses impact forces while providing optimal responsiveness and energy return to make you faster. Our unique PU foam formula offers high rebound and ultimate comfort where you need it the most. ForEverFoam is integrated in the heel to provide durability for long-lasting performance. The shoe''s minimal upper design offers lightweight flexibility and an incredibly comfortable fit. This pwrCOOL version is packed with thermo-regulation technology that helps to keep the body at an optimal temperature, preserving energy. Athletes can focus that extra energy to be faster in their sport.\r\n', 'AirMesh upper for optimised breathability.\r\n    Comfortemp for an optimum body temperature.\r\n    No-sew overlays: seamless and lightweight support.\r\n    Soft, ultra-thin suede tongue for more comfort.\r\n    Moulded EVA sockliner hugs the arch.\r\n    IGNITE Foam midsole for high-rebound cushioning.\r\n    Chevron flex grooves for increased energy return.\r\n    ForEverFoam at heel for optimal durability.\r\n    Flexibility through forefoot flex grooves.\r\n    Transition Line mimics the natural gait pattern.\r\n    Smoother toe-off for a fluid ride.\r\n    Heel to toe drop: 12mm.\r\n    EverTrack for durability in high-wear areas.', 'PumaIgniteUltimatePwrCool.jpg', 'F', 'F'),
(4, 'Adidas', 'Adidas Ultra Boost ST', '"Black", "Blue", "Grey/Green"', 150, 'M', 'Sports', 'Running', 'These Men''s running shoes are the ultimate experience in luxurious stability. Whether you''re training or running a full marathon, their plush boostâ„¢ midsole keeps every step charged with energy. An adaptive adidas Primeknit upper and ergonomic heel give lightweight support exactly where it''s needed, and a STRETCHWEB outsole provides a smooth, stable heel-to-toe transition. ', '    Weight: 9.8 ounces (size 7)\r\n    adidas Primeknit is carefully engineered to naturally expand with your foot while you run to give you a more comfortable fit and help reduce irritation\r\n    boostâ„¢''s energy-returning properties keep every step charged with an endless supply of light, fast energy\r\n    TORSIONÂ® SYSTEM for midfoot integrity; Ergonomic heel structure for added support\r\n    STRETCHWEB rubber outsole is lightweight and elastic, adapting to the ground for stability and working strategically to optimize the unique properties of boostâ„¢ from touchdown to push-off; Continentalâ„¢ Rubber outsole for extraordinary grip in wet and dry\r\n    Runner type: stable; Use: everyday trainer; Stack height: 32 mm / 24 mm (8 mm differential)\r\n    Imported', 'AdidasUltraBoostST.jpg', 'F', 'F'),
(6, 'Adidas', 'Adidas Galaxy Elite Trainers Ladies', '"Black", "Orange", "Pink", "Skyblue"', 99, 'F', 'Sports', 'Running', 'These superb adidas Galaxy Elite Trainers have been crafted with adiprene+ technology which supplies excellent cushioning and shock absorption, whilst the padded ankle collar and cushioned insole offers a comfortable fit, while the meshed panelling will help keep your feet cool. Finished off with adidas branding.', '\r\nLadies Trainers \r\nLace up fastening \r\nCushioned insole \r\nPadded ankle collar \r\nMesh panelling \r\nNon-marking sole \r\nadiPrene+ technology \r\nadiWear technology \r\nadidas branding \r\nUpper: synthetic/textile, inner: textile, sole: synthetic \r\nWipe clean with a damp cloth', 'AdidasGalaxyEliteTrainersLadies.jpg', 'T', 'F'),
(7, 'Knotty Derby', 'Knotty Derby Arthur Black Dress Shoes', '"Black", "Brown"', 125, 'M', 'Formal', 'Derby', 'Black coloured dress shoes for men by Knotty Derby. The upper of these dress shoes is made from patent leather, while the sole is made from thermoplastic rubber.', 'Color: Black\r\nUpper Material: Patent Leather\r\nSole Material: TPR\r\nClosing: Lace-up\r\nSKU: KN667SH41WTUINDFAS', 'KnottyDerbyArthurBlackDressShoes.jpg', 'F', 'F'),
(8, 'Knotty Derby', 'Knotty Derby Alastor Brown Formal Shoes', '"Brown"', 140, 'M', 'Formal', 'Derbys', 'Complete your corporate look for an upcoming boardroom meeting with these brown formal shoes by Knotty Derby. Exuding high fashion appeal, these lace-ups for men have a cushioned footbed. The rubber outsole further promises outstanding durability.', 'Color: Brown\r\nUpper Material: Synthetic Leather\r\nSole Material: Rubber\r\nClosing: Lace-up\r\nTip shape: Round\r\nAnkle Height: Low Ankle\r\nShoe Weight: Light (297 GM)\r\nProduct warranty: 3 Month Against Manufacturing Defect\r\nShoe Care: Surface Dirt can be cleaned with a good quality brush or a damp cloth.\r\nSKU: KN667SH84FXZINDFAS', 'KnottyDerbyAlastorBrownFormalShoes.jpg', 'F', 'T'),
(9, 'Knotty Derby', 'Knotty Derby Tan Oxford Formal Shoes', '"Tan"', 160, 'M', 'Formal', 'Derby', 'Spruce up your look with this pair of formal shoes by Knotty Derby. These shoes have been designed while keeping in mind the needs of the style-conscious youth. These fabulous formal shoes can be teamed with your outfit for a cool look.', 'Color: Tan\r\nUpper Material: Synthetic Leather\r\nSole Material: TPR\r\nClosing: Lace-up\r\nTip shape: Round\r\nAnkle Height: Mid Ankle\r\nProduct warranty: 3 Month Against Manufacturing Defect\r\nShoe Care: Surface Dirt can be cleaned with a good quality brush or a damp cloth.\r\nSKU: KN667SH05IOOINDFAS', 'KnottyDerbyTanOxfordFormalShoes.jpg', 'F', 'F'),
(10, 'Guess', 'Guess Viktor Derby Brown Formal Shoes', '"Brown"', 105, 'M', 'Formal', 'Derby', 'Make an impression when wearing these brown coloured formal shoes by Guess. Offering optimum traction on a wet or dry floor, its TPR (thermoplastic rubber) soles will complement the sleek design of this pair of formal shoes. Featuring synthetic upper and lining, these trendy formal sh', 'Color: Brown\r\nUpper Material: Synthetic Leather\r\nSole Material: TPR\r\nClosing: Lace-up\r\nTip shape: Round\r\nAnkle Height: Low Ankle\r\nShoe Weight: Regular (373 GM)\r\nProduct warranty3 Month Against Manufacturing Defects\r\nShoe Care: Surface Dirt can be cleaned with a good quality brush or a damp cloth.\r\nSKU: KN667SH80TTBINDFAS', 'GuessViktorDerbyBrownFormalShoes.jpg', 'F', 'F'),
(12, 'Salvatore Ferragamo', 'Salvatore Ferragamo Guillame Loafers', '"Cuoio Leather", "Nero Leather", "Rosso Leather"', 374, 'M', 'Formal', 'Loafers', 'A satin-finish Gancio bit tops a handsome Italian driving shoe fashioned from smooth leather.', '    Slip-on style.\r\n    Rubber driver sole.\r\n    Leather upper and lining/rubber sole.\r\n    By Salvatore Ferragamo made in Italy.\r\n    Men''s Shoes.', 'SalvatoreFerragamoGuillameLoafers.jpg', 'F', 'F'),
(13, 'Ermenegildo Zegna', 'Ermenegildo Zegna Loafers', '"Navy Suade", "Medium Beige Suede"', 297, 'M', 'Formal', 'Loafers', 'Creamy suede construction elevates a rich Italian driving shoe topped with leather laces.', '    Suede upper/leather lining/rubber sole.\r\n    By Ermenegildo Zegna; made in Italy.\r\n    Men''s Shoes.', 'ErmenegildoZegnaLoafers.jpg', 'F', 'F'),
(14, 'Allen Edmonds', 'Allen Edmonds Nashua Tassel Loafers', '"Black/Brown"', 195, 'M', 'Formal', 'Loafers', 'Two-tone construction elevates a smart loafer hand-crafted from premium calfskin leather and topped with charming tassels and a classic kilt.', '    Hamlet rubber sole.\r\n    Leather upper and lining/rubber sole.\r\n    By Allen Edmonds; imported.\r\n    Men''s Shoes.', 'AllenEdmondsNashuaTasselLoafers.jpg', 'F', 'F'),
(15, 'Ermenegildo Zegna', 'Ermenegildo Zegna Driving Loafers', '"Dark Red Suede", "Navy Suede"', 315, 'M', 'Formal', 'Loafers', 'Creamy suede construction elevates a rich Italian driving shoe topped with braided laces.', '    Suede upper/leather lining/rubber sole.\r\n    By Ermenegildo Zegna made in Italy.\r\n    Mens Shoes.', 'ErmenegildoZegnaDrivingLoafers.jpg', 'F', 'F'),
(16, '1901', '1901 Tyler Chukka Boots', '"Taupe Suede"', 79.9, 'M', 'Formal', 'Boots', 'Offered in weathered suede and outlined with contrast topstiching for a relaxed look, a handsome chukka boot is crafted in a sharp silhouette that pairs well with any updated casual look.', '    Lace-up style.\r\n    Breathable leather lining.\r\n    Removable insole.\r\n    Leather upper and lining/rubber sole.\r\n    By 1901 imported.\r\n    Men''s Shoes.', '1901TylerChukkaBoots.jpg', 'T', 'F'),
(17, 'Cole Haan', 'Cole Haan Weston Cap Toe Boots', '"Java Waxy Leather"', 179.9, 'M', 'Formal', 'Boots', 'Handsome contrast stitching marks a ruggedly cool boot fashioned from roughly textured leather with a smart, direct-injected sole for reliable support.', '    Lace-up style.\r\n    Leather upper and lining/rubber sole.\r\n    By Cole Haan imported.\r\n    Men''s Shoes.', 'ColeHaanWestonCapToeBoots.jpg', 'F', 'F'),
(18, 'Steve Madden', 'Steve Madden Triplyy Chukka Boots', '"Black", "Dark Brown", "Stone Brown"', 76.9, 'M', 'Formal', 'Boots', 'Burnished nubuck leather defines a classically styled chukka boot shaped in a smart silhouette for versatility.', '    Lace-up style.\r\n    Leather upper/synthetic lining/rubber sole.\r\n    By Steve Madden imported.\r\n    Men''s Shoes.', 'SteveMaddenTriplyyChukkaBoots.jpg', 'F', 'F'),
(19, 'Timberland', 'Timberland Westhaven 6 Side Zip Boots', '"Light Brown Leather"', 107.9, 'M', 'Formal', 'Boots', 'Hearty leather defines a handsome boot fitted with a smart side zipper for easy on and off and an anti-fatigue insole for all-day comfort.', '    Leather upper/textile lining/rubber sole.\r\n    By Timberland imported.\r\n    Men''s Shoes.', 'TimberlandWesthaven6SideZipBoots.jpg', 'F', 'F'),
(20, 'Converse', 'Converse Auckland Modern', '"Silver", "Blue", "Red", "Green"', 110, 'M', 'Casual', 'Sneakers', 'The Converse Auckland Modern reimagines a retro running-inspired silhouette with a lightweight knit upper and an ultra-flexible outsole to help keep you comfortable and moving freely wherever you go.', 'Light knit upper is breathable and flexible\r\nTextured sockliner for comfort\r\nMesh lining enhances breathability\r\nPhylon outsole with deep flex grooves for lightweight comfort and mobility\r\nNike Hyperfuse construction and TPU overlays for durability and support', 'ConverseAucklandModern.jpg', 'F', 'F'),
(21, 'Converse', 'Converse Chuck Taylor Low Cut Sneakers', '"Silver", "Blue", "Red", "Green", "Black", "Navy"', 49, 'M', 'Casual', 'Sneakers', 'The Converse Chuck Taylor All Star celebrates the iconic original with classic details on a comfortable canvas upper. Created in 1917 as a non-skid basketball shoe, the All Star was originally promoted for its superior court performance by basketball mastermind Chuck Taylor. But over the decades, something incredible happened: The sneaker, with its timeless silhouette and unmistakable ankle patch, was organically adopted by rebels, artists, musicians, dreamers, thinkers and originals.', 'Canvas upper for lightweight, flexible comfort\r\nRubber outsole for durable traction\r\nMedial eyelets enhance airflow', 'ConverseChuckTaylorLowCutSneakers.jpg', 'T', 'F'),
(22, 'Converse', 'Jack Purcell Signature CVO Sneaker', '"Inked Blue", "Grey"', 95, 'M', 'Casual', 'Sneakers', 'Supple suede trim marks a vintage-inspired sneaker built with Nike Zoom Air Technology for supreme comfort.', '    Lace-up style.\r\n    Removable insole.\r\n    Wool and suede upper/textile lining/rubber sole.\r\n    By Converse; imported.\r\n    Men''s Shoes.', 'JackPurcellSignatureCVOSneaker.jpg', 'F', 'F'),
(23, 'New Balance', 'New Balance 996 Distinct Mid-Century', '"Desert Brown"', 155, 'M', 'Casual', 'Sneakers', 'The New Balance 996 has always been a staple in NBâ€™s retro running category, and today a classic combination of suede and mesh hits in one of the cleanest offerings in recent memory. A durable white suede serves as the base throughout while breathable mesh hits on the toe, tongue, and ankle collar. Accents of dark grey and obsidian hit the branding and ENCAPÂ® midsole. Are you a fan of the look? Continue onward for a better look at the latest NB 996 below and pick up this pair from select shops like Sole Mate today for $155', '- Faux suede, textile upper upper\r\n- Round toe\r\n- Lace up fastening\r\n- 7 pairs of eyelets\r\n- Flat lace\r\n- Textile insole', 'NewBalance996DistinctMid-CenturyModern.jpg', 'F', 'T'),
(25, 'Toysrus', 'New Balance Boys Sneakers', '"Silver", "Blue", "Red", "Green", "Black", "Navy"', 40, 'Y', 'Boys', 'Select Sub-Category', 'For the perfect pair of shoes that can go with any outfit, Skechers has brought your little kid the Gains slip-on. With the stylish design, he can wear them with a pair of jeans or slacks!', '\r\nLeather upper\r\nSlip-on style with elastic side panels\r\nHeel pull tab for easy on and off\r\nStitching details\r\nFaux leathering lining\r\nRelaxed fit memory foam insole for the ultimate support\r\nPU traction sole\r\nImported', 'NewBalanceBoysSneakers.jpg', 'F', 'T'),
(26, 'Sketchers', 'Sketchers Boys Sneakers', '"Black", "Brown"', 30, 'Y', 'Boys', 'Select Sub-Category', 'For the perfect pair of shoes that can go with any outfit, Skechers has brought your little kid the Gains slip-on. With the stylish design, he can wear them with a pair of jeans or slacks!', '\r\nLeather upper\r\nSlip-on style with elastic side panels\r\nHeel pull tab for easy on and off\r\nStitching details\r\nFaux leathering lining\r\nRelaxed fit memory foam insole for the ultimate support\r\nPU traction sole\r\nImported', 'SketchersBoysSneakers.jpg', 'F', 'F'),
(27, 'New Balance', 'New Balance Girls Sneakers', '"Pink"', 30, 'Y', 'Girls', 'Select Sub-Category', 'For the perfect pair of shoes that can go with any outfit, Skechers has brought your little kid the Gains slip-on. With the stylish design, he can wear them with a pair of jeans or slacks!', 'Leather upper\r\nSlip-on style with elastic side panels\r\nHeel pull tab for easy on and off\r\nStitching details\r\nFaux leathering lining\r\nRelaxed fit memory foam insole for the ultimate support\r\nPU traction sole\r\nImported', 'NewBalanceGirlsSneakers.jpg', 'T', 'F'),
(28, 'Hello Kitty', 'Hello Kitty Girls Shoes', '"Pink"', 20, 'Y', 'Girls', 'Select Sub-Category', 'Hello Kitty is a fictional character produced by the Japanese company Sanrio, created by Yuko Shimizu and currently designed by Yuko Yamaguchi. She is depicted as an anthropomorphic white Japanese Bobtail cat with a red bow.', 'Leather upper\r\nSlip-on style with elastic side panels\r\nHeel pull tab for easy on and off\r\nStitching details\r\nFaux leathering lining\r\nRelaxed fit memory foam insole for the ultimate support\r\nPU traction sole\r\nImported', 'HelloKittyGirlsShoes.jpg', 'F', 'F'),
(29, 'Hello Kitty', 'Hello Kitty Girls Slip-Ons', '"Magenta"', 35, 'G', 'Select Category', 'Select Sub-Category', 'Hello Kitty (Japanese: ãƒãƒ­ãƒ¼ãƒ»ã‚­ãƒ†ã‚£ Hepburn: HarÅ Kiti?),[4] (full name: Kitty White (ã‚­ãƒ†ã‚£ãƒ»ãƒ›ãƒ¯ã‚¤ãƒˆ Kiti Howaito?))[3] is a fictional character produced by the Japanese company Sanrio, created by Yuko Shimizu and currently designed by Yuko Yamaguchi. She is depicted as an anthropomorphic white Japanese Bobtail cat with a red bow.[5]', 'Leather upper\r\nSlip-on style with elastic side panels\r\nHeel pull tab for easy on and off\r\nStitching details\r\nFaux leathering lining\r\nRelaxed fit memory foam insole for the ultimate support\r\nPU traction sole\r\nImported', 'HelloKittyGirlsSlip-Ons.jpg', 'F', 'F'),
(31, 'Adidas', 'Adidas Originals Dragon Boys Shoes', '"Onix/Semi Solar Green/Core White"', 50, 'Y', 'Boys', 'Select Sub-Category', 'Brand: adidas\r\nType: Sandals\r\nAges: 3-12 years old', 'SKU: 465467746513468', 'AdidasOriginalsDragonBoysShoes.jpg', 'F', 'F'),
(32, 'Shimano', ' Shimano RP5 SPD-SL  Womens Road Shoes', '"Black", "White"', 250, 'F', 'Sports', 'Cycling', 'Shimano are the makers of the world''s most well known cycle component brand. Established in 1921 when the first cycle freewheel was forged. Shimano produce drivetrains, wheels, pedals, shoes, cycling apparel and pretty much every Shimano cycle accessory you can think of! Famous for their top end products ridden by the pro''s, Dura-Ace and XTR, which cover both road and MTB''s. At Shimano, they''re doing everything they can to respond to heightened environmental concerns. Shimano are proud to be a producer of bicycle components that help people to enjoy outdoor sports and interact with nature through healthy nonpolluting activities. In their 87 plus years of existence Shimano have accumulated a wealth of technology and product development and expertize that serves as the driving force behind their continually evolving product line.', '\r\n    Weight: 507g per pair (Size 40)\r\n    Compatible with SPD and SPD-SL cleats\r\n    All day comfort\r\n    Adaptable closure system\r\n    Functional Performance\r\n    Glass fiber reinforced nylon sole\r\n    Carbon fiber composite plate\r\n\r\n', 'ShimanoRP5SPD-SLRoadShoes.jpg', 'F', 'F'),
(36, 'Cherokee', 'Cherokee Toddler Girls Jan Bow Thong Sandals ', '"Turquoise", "White"', 21.5, 'Y', 'Girls', 'Select Sub-Category', 'These sweet and lightweight Toddler Girls'' Jan Bow Thong Sandals in Assorted Colors are perfect for summer. They feature a cute bow detail, shiny patent finish, polyurethane and rubber construction, comfy insole and hook and loop closure on the ankle strap.', '    Sizing: Toddler (2T - 5T)\r\n    Width: Medium\r\n    Construction: Adjustable strap\r\n    Upper Material: 99 % Polyurethane,\r\n    Outsole Material: 100 % Thermoplastic rubber,\r\n    Insole Material: Polyurethane\r\n    Lining Material: Polyurethane\r\n    Closure Style: Hook and loop closure\r\n    Strap Style: Ankle strap\r\n    No heel\r\n    Care and Cleaning: Avoid extreme heat\r\n', 'CherokeeToddlerGirlsJanBowThongSandals.jpg', 'T', 'F'),
(37, 'Sidi', 'Sidi Kaos Air Road Shoe', '"Blue", "Lime Green"', 160, 'M', 'Sports', 'Cycling', 'A stiff carbon sole and Tecno 3 Buckle system make this a comfortable and lightweight road shoe.', '\r\nTop Features of the Sidi Kaos Air Road Shoe\r\n\r\n    Soft Instep 2\r\n    Caliper Buckle\r\n    Tecno 3 System\r\n    Replaceable Heel Pad\r\n\r\n', 'SidiKaosAirRoadShoe.jpg', 'F', 'T'),
(38, 'Shimano', ' Shimano RP5 SPD-SL Road Shoes', '"Black", "White"', 250, 'M', 'Sports', 'Cycling', 'Shimano are the makers of the world''s most well known cycle component brand. Established in 1921 when the first cycle freewheel was forged. Shimano produce drivetrains, wheels, pedals, shoes, cycling apparel and pretty much every Shimano cycle accessory you can think of! Famous for their top end products ridden by the pro''s, Dura-Ace and XTR, which cover both road and MTB''s. At Shimano, they''re doing everything they can to respond to heightened environmental concerns. Shimano are proud to be a producer of bicycle components that help people to enjoy outdoor sports and interact with nature through healthy nonpolluting activities. In their 87 plus years of existence Shimano have accumulated a wealth of technology and product development and expertize that serves as the driving force behind their continually evolving product line.', '\r\n    Weight: 507g per pair (Size 40)\r\n    Compatible with SPD and SPD-SL cleats\r\n    All day comfort\r\n    Adaptable closure system\r\n    Functional Performance\r\n    Glass fiber reinforced nylon sole\r\n    Carbon fiber composite plate\r\n\r\n', 'ShimanoRP5SPD-SLRoadShoes.jpg', 'F', 'F'),
(39, 'Shimano', 'Shimano WR84 SPD-SL Womens Shoes', '"Black", "White"', 190, 'F', 'Sports', 'Cycling', 'Supple stretch resistant synthetic leather upper\r\nOpen mesh for optimal breathability\r\nLow-profile micro-adjust buckle and dual off-set straps for easy and accurate adjustment\r\nEnhanced profile and dual density insoles for excellent biomechanical support\r\nShimano Dynalast technology sole gives an additional 11mm of cleat adjustment compared to previous models\r\nNew wrap around upper design reduces drag and evenly distributes tension across the foot\r\nLightweight carbon fibre sole construction for excellent stiffness to weight ratio incorporating adjustable cleat mounts', '\r\n    Weight: 486g per pair (Size 40)\r\n    Stiff Carbon Fibre Sole\r\n    Extra 11mm cleat adjustment\r\n    Lightweight shoe\r\n    Supple leather upper\r\n    Breathable\r\n    Micro-adjust buckle\r\n    Dual off-set straps\r\n    Dual density insoles\r\n    Shimano Dynalast sole\r\n    Wrap around upper design\r\n\r\n', 'ShimanoWR84SPD-SLWomensShoes.jpg', 'F', 'F'),
(41, 'Sidi', 'Sidi Kaos Air Road Womens Shoe', '"Blue", "Lime Green"', 160, 'F', 'Sports', 'Cycling', 'A stiff carbon sole and Tecno 3 Buckle system make this a comfortable and lightweight road shoe.', '\r\nTop Features of the Sidi Kaos Air Road Shoe\r\n\r\n    Soft Instep 2\r\n    Caliper Buckle\r\n    Tecno 3 System\r\n    Replaceable Heel Pad\r\n\r\n', 'SidiKaosAirRoadShoe.jpg', 'F', 'T'),
(42, 'Sidi', 'Sidi Ergo 4 Carbon Road Shoes', '"Black", "White"', 170, 'M', 'Sports', 'Cycling', 'MEGA FIT\r\nMega is the Sidi version of Wide Fit. Buying the Mega version gives you the following:\r\nâ€¢ 4 mm wider across the ball of the foot\r\nâ€¢ More volume, a high instep and a wider heel cup\r\nâ€¢ Mega lasts are EE o EEE width\r\n\r\nThe TECHNO-3 SYSTEM dials in fit along the entire length of the shoe, adapting the upper to the shape of the foot for a customized fit. SIDIâ€™s famously reliable and replaceable closures are improved by an all new proprietary SIDI Wire material that is completely nonbinding for intuitive and effortless on-the-fly adjustments. Like most SIDI small parts, the TECNO-3 SYSTEM is serviceable and replaceable.\r\n\r\nThe SOFT INSTEP CLOSURE SYSTEM is a wide, anatomically curved strap combined with a soft, thermoformed EVA pad that distributes pressure evenly over the instep area. The SOFT INSTEP CLOSURE SYSTEM is adjustable from both sides, to perfectly center the EVA pad over a high or low instep. The system eliminates the need for the High Instep Extender. The SOFT INSTEP CLOSURE SYSTEM is replaceable.\r\n\r\nHIGH SECURITY VELCRO straps with integrated locking polymer teeth, that engage onto each other when the strap is closed. This feature makes the closure more secure and the strap becomes unmoveable.\r\n\r\nThe ADJUSTABLE HEEL RETENTION DEVICE reinforces the top of the heel cup and improves the fit by closing the back of the shoe securely around the riderâ€™s heel. The heel retention device tightens the top of the heel cup so that the heel doesnâ€™t slide out during steep climbs or sprints. Each side of the heel can be adjusted independently, for a perfect fit. For a custom adjustment turn the screw towards the + sign to tighten the heel retention device and towards the â€“ sign to open it. Light weight, easy to use, and replaceable.\r\n\r\nReinforced SIDI HEEL CUP that stabilizes and supports the heel. Anatomically shaped plastic, reduces heel slip and provides increased power transfer. Provides additional foot protection in the event of a crash.\r\n\r\nFor walkability, Sidi cycling shoes include a polyurethane REPLACEABLE HEEL PAD.\r\n\r\nTWELVE CARBON COMPOSITE SOLE is made with two different materials blended together, nylon and carbon fibre. It is made out of injected Carbon Fiber in a matrix of Nylon. The Nylon used doesnâ€™t absorb water and doesnâ€™t lose rigidity in hot or humid weather or as it ages. The result is a significantly lighter and stiffer sole.', '\r\n    Mega/Wide Fit\r\n    Tecno-3 System\r\n    Soft Instep 3 Closure System\r\n    High Security Velcro\r\n    Adjustable Heel Retention Device\r\n    Replaceable Heel\r\n    Sidi Heel Cup\r\n    Twelve Carbon Composite Sole\r\n\r\n', 'SidiErgo4CarbonRoadShoes.jpg', 'F', 'F'),
(43, 'Converse', 'Converse Chuck Taylor Low Cut Sneakers', '"Silver", "Blue", "Red", "Green", "Black", "Navy"', 49, 'F', 'Casual', 'Sneakers', 'The Converse Chuck Taylor All Star celebrates the iconic original with classic details on a comfortable canvas upper. Created in 1917 as a non-skid basketball shoe, the All Star was originally promoted for its superior court performance by basketball mastermind Chuck Taylor. But over the decades, something incredible happened: The sneaker, with its timeless silhouette and unmistakable ankle patch, was organically adopted by rebels, artists, musicians, dreamers, thinkers and originals.', 'Canvas upper for lightweight, flexible comfort\r\nRubber outsole for durable traction\r\nMedial eyelets enhance airflow', 'ConverseChuckTaylorLowCutSneakers.jpg', 'T', 'F'),
(44, 'Burberry', 'Burberry Mawdesley', '"Beige"', 270, 'F', 'Formal', 'Heels', 'Shimano are the makers of the world''s most well known cycle component brand. Established in 1921 when the first cycle freewheel was forged. Shimano produce drivetrains, wheels, pedals, shoes, cycling apparel and pretty much every Shimano cycle accessory you can think of! Famous for their top end products ridden by the pro''s, Dura-Ace and XTR, which cover both road and MTB''s. At Shimano, they''re doing everything they can to respond to heightened environmental concerns. Shimano are proud to be a producer of bicycle components that help people to enjoy outdoor sports and interact with nature through healthy nonpolluting activities. In their 87 plus years of existence Shimano have accumulated a wealth of technology and product development and expertize that serves as the driving force behind their continually evolving product line.', 'Weight: 486g per pair (Size 40)\r\n    Stiff Carbon Fibre Sole\r\n    Extra 11mm cleat adjustment\r\n    Lightweight shoe\r\n    Supple leather upper\r\n    Breathable\r\n    Micro-adjust buckle\r\n    Dual off-set straps\r\n    Dual density insoles\r\n    Shimano Dynalast sole\r\n    Wrap around upper design', 'BurberryMawdesley.jpg', 'F', 'F'),
(45, 'Christian Louboutin', 'Christian Louboutin So Kate', '"Black"', 125, 'F', 'Formal', 'Heels', 'Shimano are the makers of the world''s most well known cycle component brand. Established in 1921 when the first cycle freewheel was forged. Shimano produce drivetrains, wheels, pedals, shoes, cycling apparel and pretty much every Shimano cycle accessory you can think of! Famous for their top end products ridden by the pro''s, Dura-Ace and XTR, which cover both road and MTB''s. At Shimano, they''re doing everything they can to respond to heightened environmental concerns. Shimano are proud to be a producer of bicycle components that help people to enjoy outdoor sports and interact with nature through healthy nonpolluting activities. In their 87 plus years of existence Shimano have accumulated a wealth of technology and product development and expertize that serves as the driving force behind their continually evolving product line.', 'Weight: 486g per pair (Size 40)\r\n    Stiff Carbon Fibre Sole\r\n    Extra 11mm cleat adjustment\r\n    Lightweight shoe\r\n    Supple leather upper\r\n    Breathable\r\n    Micro-adjust buckle\r\n    Dual off-set straps\r\n    Dual density insoles\r\n    Shimano Dynalast sole\r\n    Wrap around upper design', 'ChristianLouboutinSoKate.jpg', 'F', 'F'),
(46, 'Prada', 'Prada Pointy Toe Pumps', '"Black", "Dark Blue", "Red"', 210, 'F', 'Formal', 'Pumps', 'A tall stiletto heel balances this bewitching pump designed with subtle curves and a perfectly pointed toe.\r\n\r\n  ', '  3 1/2" (85mm) heel (size 38.5).\r\n    Leather upper, lining and sole.\r\n    By Prada; made in Italy.\r\n    Salon Shoes.', 'PradaPointyToePumps.jpg', 'F', 'T'),
(48, 'Charles by Charles David', 'Lava Mary Jane Pump (Women)', '"Black", "Dark Blue", "Red"', 110, 'F', 'Formal', 'Pumps', 'A lush suede pump channels retro ''90s style with a buckled mary jane strap, while a tall stiletto heel keeps the classic silhouette in the here-and-now.', '    4" heel (size 8.5).\r\n    Adjustable strap with buckle closure.\r\n    Cushioned footbed.\r\n    Suede upper/synthetic lining and sole.\r\n    By Charles by Charles David; imported.\r\n    Women''s Shoes.', 'LavaMaryJanePump(Women).jpg', 'F', 'F'),
(49, 'Louise et Cie', 'Esperance Pump (Women)', '"Ruby Print", "Black", "Grey"', 177, 'F', 'Formal', 'Pumps', 'A skinny ankle strap tops a lofty pump crafted with a trend-right pointed toe and walkable heel.', '    2 3/4" heel (size 8.5).\r\n    3" ankle strap height.\r\n    Adjustable ankle strap with buckle closure.\r\n    Leather upper and lining/synthetic sole.\r\n    By Louise et Cie; imported.\r\n    Women''s Shoes.', 'EsperancePump(Women).jpg', 'F', 'T'),
(50, 'New Look', 'Black Suedette Peep Toe Wedges ', '"Black", "Nude"', 59.99, 'F', 'Formal', 'Wedges', 'Man Made.\r\nSoft suedette finish\r\nPeep toe design\r\nCut out sides\r\nWedge heel height: 4"/10cm\r\nSoft suedette finish\r\nPeep toe design', '- Soft suedette finish\r\n- Peep toe design\r\n- Cut out sides\r\n- Wedge heel height: 4"/10cm\r\n- Soft suedette finish\r\n- Peep toe design\r\n- Cut out sides\r\n- Wedge heel height: 4"/10cm\r\n- Product Code: 382116701', 'BlackSuedettePeepToeWedges.jpg', 'F', 'F'),
(51, 'New Look', 'Light Brown Suedette Ghillie Block Heels ', '"Black", "Nude"', 65.9, 'F', 'Formal', 'Heels', '- Soft suedette finish\r\n- Lace up fastening\r\n- Open toe\r\n- Block heel\r\n', '\r\n\r\nProduct Code: 382577121\r\n\r\nCare Guide:\r\n\r\nMan Made.', 'LightBrownSuedetteGhillieBlockHeels.jpg', 'F', 'F'),
(52, 'New Look', 'Pink Embellished Strappy Wedge Sandals ', '"Beige"', 79, 'F', 'Formal', 'Wedges', '- Embellished trim\r\n- Strappy design\r\n- Heel height: 4"/10cm', '- Embellished trim\r\n- Strappy design\r\n- Heel height: 4"/10cm\r\n\r\nProduct Code: 382013814\r\n\r\nCare Guide:\r\n\r\nMan Made.\r\n', 'PinkEmbellishedStrappyWedgeSandals.jpg', 'F', 'F'),
(53, 'SODA', 'SODA Jorgina Womens Wedges', 'Tan', 49.9, 'F', 'Formal', 'Wedges', 'Soda Jorgina wedges', 'Strappy crossing faux leather upper. Zip back heel. Covered faux leather wedge heel. Approx 1.5"(4cm) midsole gives rise to a 4.75"(12cm) heel. Rubber outsole. Imported.', 'SODAJorginaWomensWedges.jpg', 'F', 'F'),
(54, 'Birkenstock', ' Milano Habana Oiled Leather Womens', '"Brown"', 125, 'F', 'Casual', 'Sandals', 'The Milano is similar to our iconic Arizona but the added heel strap helps it stay on your foot a bit better. All three straps have an adjustable buckle for a great fit. Offered in classic footbed in Habana Oiled Leather. Made in Germany. ', 'Upper material: Oiled Leather - thick yet supple leather is breathable, durable and comfortable. Softens with wear.\r\nFootbed: The classic Birkenstock footbed - features pronounced arch support, a deep heel cup, and a roomy toe box. The footbed conforms to the shape of your foot.\r\n    Sole material: EVA - flexible, lightweight, durable and shock absorbing.\r\n', 'MilanoHabanaOiledLeather.jpg', 'F', 'F'),
(55, 'Birkenstock', ' Gizeh Habana Oiled Leather Womens', '"Brown"', 152, 'F', 'Casual', 'Sandals', 'The Gizeh is our most iconic thong sandal with a stylish but clean look that''s perfect for almost any outfit. The toe piece is made of flexible resin, anatomically designed to fit comfortably between the toes and the strap has a buckle for a secure fit. Offered in classic footbed in Habana Oiled Leather. ', 'Upper material: Oiled Leather - thick yet supple leather is breathable, durable and comfortable. Softens with wear.\r\nFootbed: The classic Birkenstock footbed - features pronounced arch support, a deep heel cup, and a roomy toe box. The footbed conforms to the shape of your foot.\r\nSole material: EVA - flexible, lightweight, durable and shock absorbing.\r\n', 'GizehHabanaOiledLeather.jpg', 'F', 'F'),
(56, 'Birkenstock', ' Arizona Soft Footbed Brown Amalfi Leather Womens', '"Brown"', 135, 'F', 'Casual', 'Sandals', 'Our iconic two-strap style, the Arizona, is known for being the epitome of comfort. Both straps have buckles for a fantastic fit. Offered in soft footbed in Brown Amalfi Leather. Made in Germany. ', 'Upper material: Amalfi Leather - thick yet supple leather that is breathable, durable and comfortable.\r\nFootbed: Soft footbed - a foam layer is inserted between the cork layer and the suede liner of the classic Birkenstock footbed. This layer features an extremely high degree of rebound capacity which permits long-lasting cushioning.\r\nSole material: EVA - flexible, lightweight, durable and shock absorbing.\r\n', 'ArizonaSoftFootbedBrownAmalfiLeather.jpg', 'F', 'F'),
(57, 'Converse', 'Jack Purcell Signature Womens CVO Sneakers', '"Inked Blue", "Grey"', 95, 'F', 'Casual', 'Sneakers', 'Supple suede trim marks a vintage-inspired sneaker built with Nike Zoom Air Technology for supreme comfort.', '    Lace-up style.\r\n    Removable insole.\r\n    Wool and suede upper/textile lining/rubber sole.\r\n    By Converse; imported.\r\n    Men''s Shoes.', 'JackPurcellSignatureCVOSneaker.jpg', 'F', 'F'),
(58, 'New Balance', 'New Balance 996 Distinct Mid-Century Womens', '"Desert Brown"', 155, 'F', 'Casual', 'Sneakers', 'The New Balance 996 has always been a staple in NBâ€™s retro running category, and today a classic combination of suede and mesh hits in one of the cleanest offerings in recent memory. A durable white suede serves as the base throughout while breathable mesh hits on the toe, tongue, and ankle collar. Accents of dark grey and obsidian hit the branding and ENCAPÂ® midsole. Are you a fan of the look? Continue onward for a better look at the latest NB 996 below and pick up this pair from select shops like Sole Mate today for $155', '- Faux suede, textile upper upper\r\n- Round toe\r\n- Lace up fastening\r\n- 7 pairs of eyelets\r\n- Flat lace\r\n- Textile insole', 'NewBalance996DistinctMid-CenturyModernWomens.jpg', 'F', 'T'),
(59, 'Toms', 'Spiced Coral Canvas Womens Classics', '"Pink"', 59, 'F', 'Casual', 'Palms', 'Featuring a new hue that youâ€™ll wear year-round, the Classic Alpargata is best known for being the shoe that started the One for OneÂ® movement.\r\n\r\n    Spiced coral canvas upper\r\n    Elastic â€œVâ€ for easy fit\r\n    Suede footbed\r\n    Rubber outsole provides a no-slip grip', 'TOMS run true to size and are available in medium width only. We recommend ordering the size you normally wear. If you are typically in between sizes, we recommend going with the smaller one since TOMS will stretch slightly as you break them in.', 'SpicedCoralCanvasWomensClassics.jpg', 'F', 'F'),
(60, 'KEEN', 'KEEN Womens City of Palms', '"Brown"', 95, 'F', 'Casual', 'Palms', 'Fit Tip: Most customers find this style is true to size!\r\nMeasurement Note: Our measurements were taken using a Womenâ€™s size 7 US (37.5 EU). Measurements may vary by size.', 'Approximate weight per shoe: 5.8 oz/ 164 g\r\nStyle: Sandals\r\nCollections: Casual\r\nCategory: Casual\r\nActivity: City, Beach\r\nWeather: Warm\r\nGender: Women\r\nUpper: Leather', 'KEENWomensCityofPalms.jpg', 'F', 'F'),
(61, 'Taylor Palm', 'Off White Womens Palms', '"White"', 36, 'F', 'Casual', 'Palms', 'Building on the popular man-tailored trend, this T-bar style is a great transitional choice. A metallic buckle fastening, surface detailing and a low heel add glamorous touches while Cushion Softâ„¢ layers provide a comfortable fit. The off white patent and dainty pointed toe finish the look. Take a look at our blog for ideas on how to style this shoe.', 'Upper Material: 	Leather\r\nLining Material:	Textile\r\nHeel Height: 1 inch\r\nSole Material: TR\r\nFastening Type: Buckle\r\nRemovable Insole: No\r\nTrims: Adjustable Strap, Buckle', 'OffWhiteWomensPalms.jpg', 'F', 'F'),
(62, 'Nike', 'Nike Free RN Motion Flyknit', '"Jade", "Blue", "Oreo"', 150, 'F', 'Sports', 'Running', 'Nike''s most natural ride to date, the Nike Free RN Motion Flyknit Women''s Running Shoe features a supportive, conforming Flyknit upper and a revolutionary new midsole pattern that allows the shoe to expand, flex and contract with your foot during every stepâ€”so you can move more freely than ever before.\r\n\r\nSuperior Natural Movement\r\n\r\nThe next-generation Nike Free midsole expands in multiple directions thanks to an entirely new tri-star pattern, adding a new dimension of flexibility that delivers maximum dynamic movement with every stride. Plus, the heel is rounded to mimic the shape of your foot and roll naturally with the ground.\r\n\r\nEnhanced Cushioning\r\n\r\nThe dual-density midsole uses a softer foam core directly underfoot and a slightly firmer foam carrier to deliver cushioned comfort and durability for a smooth, natural ride.\r\n\r\nSnug Fit\r\n\r\nStrong, single-seam Flyknit includes stretchy polyester yarn for a compressive fit that moves flawlessly with your foot as you run. Flywire cables woven into the upper can be tightened through the laces for dynamic support.', 'Notched collar for easy on and off\r\nRounded heel for natural range of motion\r\nLightweight solid rubber segments under the toe and heel for enhanced traction and durability\r\nOffset: 4mm', 'NikeFreeRNMotionFlyknit.jpg', 'F', 'F'),
(63, 'Nike', 'Nike Free Running Shoes', '"Black/Green", "Volt"', 100, 'F', 'Sports', 'Running', 'More cushioned than the Nike Free RN Motion Flyknit, the Nike Free RN Women''s Running Shoe features a newly designed midsole pattern that expands, flexes and contracts with your foot with every step. Its lightweight, breathable mesh upper helps keep your feet cool and comfortable from start to finish.\r\n\r\nMove Naturally\r\n\r\nThe next-generation Nike Free midsole expands in multiple directions thanks to an entirely new tri-star pattern, adding a new dimension of flexibility that lets your feet move more dynamically with every stride. Plus, the heel is rounded to mimic the shape of your foot and roll naturally with the ground.\r\n\r\nSoft Cushioning\r\n\r\nSofter than previous iterations, the new midsole foam delivers exceptionally comfortable cushioning and lightweight durability for miles.\r\n\r\nFlexible, Breathable Support\r\n\r\nEngineered mesh provides lightweight, flexible support and breathable comfort. Flywire cables integrate with the laces and can be adjusted for an adaptive fit.', 'Minimal sockliner molds to the shape of your foot for added support\r\nLightweight solid rubber segments under the toe and heel for enhanced traction and durability\r\nWeight: 6.9 ounces (women''s size 8)', 'NikeFreeRunningShoes.jpg', 'F', 'F'),
(64, 'Nike', 'Nike Flyknit Air Max Womens', '"White/Black", "Pink/Blue"', 225, 'F', 'Sports', 'Training', 'Ultralight support meets maximum cushioning in the Nike Flyknit Air Max Women''s Running Shoe, featuring the most flexible Max Air unit yet and a woven one-piece Flyknit upper.\r\n\r\nMaximum, Flexible Cushioning\r\n\r\nThe full-length Max Air unit offers the most flexibility to date while still delivering maximum cushioning for ultimate comfort on your run. Its tubular construction allows more air underfoot to encourage even transitions from heel strike through toe-off.\r\n\r\nUltralight Support\r\n\r\nThe ultralight Flyknit upper contours to your foot for a comfortable, supportive fit. Made entirely of polyester yarn, the single-layer construction seamlessly integrates areas of high breathability, stretch and support where you need it most.\r\n\r\nSmooth Ride\r\n\r\nThe lighter Waffle pattern outsole has been redesigned to distribute your weight more evenly for a smoother ride and enhanced traction.', 'Flywire technology integrates with the laces for a dynamic, supportive fit\r\nStitch and turn collar for a snug, comfortable fit\r\nSculpted Cushlon midsole for plush cushioning, springy resilience and impact protection\r\nFlex grooves align with the Max Air unit for more natural range of motion\r\nReflective elements enhance visibility in low light', 'NikeFlyknitAirMaxWomens.jpg', 'F', 'F'),
(65, 'Nike', 'Nike FS Lite Run 3', '"Black Pink", "Pink Blast"', 60, 'F', 'Sports', 'Training', 'The Nike FS Lite Run 3 Women''s Running Shoe is made with Breathe Tech for lightweight support. No-sew overlays, flex grooves and responsive cushioning enhance comfort and movement for your run.\r\n\r\nBenefits\r\nMidfoot Breathe Tech construction fuses foam and mesh for a lightweight support\r\nDual-density foam midsole for lightweight, responsive cushioning\r\nNo-sew overlays offer support and enhanced breathability\r\nHexagonal lugs provide multi-surface traction\r\nTargeted rubber outsole pods for enhanced durability\r\nFlex grooves promote natural range of motion', 'Weight: 7.15 ounces (women''s size 8)\r\nOffset: 3mm', 'NikeFSLiteRun3.jpg', 'T', 'F'),
(66, 'Nike', 'Nike Zoom Streak LT 3', '"Blue", "Lime Green"', 80, 'F', 'Sports', 'Training', 'The Nike Zoom Streak LT 3 Racing Shoe is built with a new last and wider forefoot to increase toe spring. This update works with the midfoot shank to add even more response off multiple surfaces.\r\n\r\nAvailable in men''s sizes. Reference the Size Chart above to convert a women''s size to men''s. ', 'Engineered mesh with an arch band locks the foot down\r\nUpdated last has more room in the forefoot to enhance toe spring\r\nFull-length Cushlon midsole with Nike Zoom unit in the heel for ultra-lightweight, responsive cushioning\r\nMidfoot shank for snappy response\r\nCrash rail and decoupled toe encourage a smooth transition\r\nBlown rubber Waffle outsole for durable, firmer cushioning and traction', 'NikeZoomStreakLT3.jpg', 'F', 'F'),
(67, 'Birkenstock', ' Arizona Soft Footbed Brown Amalfi Leather', '"Brown"', 135, 'M', 'Casual', 'Sandals', 'Our iconic two-strap style, the Arizona, is known for being the epitome of comfort. Both straps have buckles for a fantastic fit. Offered in soft footbed in Brown Amalfi Leather. Made in Germany. ', 'Upper material: Amalfi Leather - thick yet supple leather that is breathable, durable and comfortable.\r\nFootbed: Soft footbed - a foam layer is inserted between the cork layer and the suede liner of the classic Birkenstock footbed. This layer features an extremely high degree of rebound capacity which permits long-lasting cushioning.\r\nSole material: EVA - flexible, lightweight, durable and shock absorbing.\r\n', 'ArizonaSoftFootbedBrownAmalfiLeather.jpg', 'F', 'F'),
(68, 'Birkenstock', ' Milano Habana Oiled Leather', '"Brown"', 125, 'M', 'Casual', 'Sandals', 'The Milano is similar to our iconic Arizona but the added heel strap helps it stay on your foot a bit better. All three straps have an adjustable buckle for a great fit. Offered in classic footbed in Habana Oiled Leather. Made in Germany. ', 'Upper material: Oiled Leather - thick yet supple leather is breathable, durable and comfortable. Softens with wear.\r\nFootbed: The classic Birkenstock footbed - features pronounced arch support, a deep heel cup, and a roomy toe box. The footbed conforms to the shape of your foot.\r\n    Sole material: EVA - flexible, lightweight, durable and shock absorbing.\r\n', 'MilanoHabanaOiledLeather.jpg', 'F', 'F'),
(69, 'ACME', 'Triple Straps Sandals', '"Black", "Brown"', 29.9, 'M', 'Casual', 'Sandals', 'Ready to be cool and free with this pair of sandals from ZALORA. Featuring minimal design with buckle details, these trendy sandals are sure to complement your everyday ensemble.', 'Synthetic upper\r\n- Open toecap\r\n- Synthetic suede leather insole with brand detail\r\n- Synthetic outsole', 'TripleStapsSandals.jpg', 'F', 'F'),
(70, 'Nike', 'Nike Romaleos 2', '"White/Black", "Flouroscent Yellow"', 189, 'M', 'Sports', 'Training', 'The Nike Romaleos 2 Men''s Weightlifting Shoe delivers maximum support and a locked-in fit in the gym with integrated lacing, two large midfoot bands and a honeycomb midsole. An innovative thermoplastic heel wedge replaces the wooden version that has been in weightlifting shoes since the 1960s.', 'Synthetic upper for durability and support\r\nIntergrated lacing and two large hook-and-loop midfoot bands for a locked-in feel\r\nElastic on the top of the inside of the shoe flexes with your foot tendons during the snapping "triple extension" movement of the clean and jerk\r\nHoneycomb-like system of trusses and bridges in the midsole for maximum stability\r\nContoured, thermoplastic heel wedge ensures the optimal receiving position and provides maximum support without compression\r\nTwo different sockliners give you versatility for training (softer) and competition (firmer)', 'NikeRomaleos2.jpg', 'F', 'T'),
(71, 'Nike', 'Nike Free Train Versatility', '"Black/Total Orange/Volt"', 90, 'M', 'Sports', 'Training', 'The Nike Free Train Versatility Men''s Training Shoe gives you the flexible support you need for intense and varied workouts. A warp knit upper with Flywire cables offers powerful lockdown, while a revolutionary Nike Free outsole expands and contracts with your foot on every landing.', 'No-sew overlays add lightweight support and durability\r\nHeel loop for easy on and off\r\nDurable Phylon midsole doubles as an outsole for lightweight comfort\r\nMolded sockliner mimics the curvature of the foot for added support\r\nRubber reinforcements enhance durability in key areas\r\nRounded, anatomical heel helps you move naturally', 'NikeFreeTrainVersatility.jpg', 'F', 'F'),
(72, 'Nike ', ' Nike Train Quick Mens', '"Black/Pink/Yellow"', 139.99, 'M', 'Sports', 'Training', 'Make your quickness a weapon during your workouts with these responsive, innovative training shoes.', '\r\n    Molded upper features Flywire tech for a lightweight and innovative lockdown.\r\n    Low-profile IU Foam midsole with recessed PebaxÂ® plate in the forefoot propels your foot forward.\r\n    Rubber outsole lets you accelerate and decelerate on a dime.\r\n', 'NikeTrainQuickMens.jpg', 'T', 'F'),
(73, 'wewqewqeq', 'qewewqewwe', '"dahuiwda"', 176, 'M', 'Casual', 'Sneakers', 'dwdawdawdawdawdawddwa', 'wddawdawdawdawwaddawdawdawdaaw', 'qewewqewwe.jpg', 'F', 'T');

-- --------------------------------------------------------

--
-- Table structure for table `user_details`
--

CREATE TABLE IF NOT EXISTS `user_details` (
  `firstname` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `gender` enum('M','F','O') NOT NULL,
  `dob` date NOT NULL,
  `profile_picture` varchar(255) NOT NULL,
  `adminRights` enum('T','F') DEFAULT 'F',
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user_details`
--

INSERT INTO `user_details` (`firstname`, `lastname`, `username`, `password`, `email`, `gender`, `dob`, `profile_picture`, `adminRights`) VALUES
('', 'asdf123', '1', '', 'asdf@mail.com', 'O', '2012-02-12', '1.jpg', 'F'),
('admin', 'admin', 'admin', 'admin', 'admin@mail.com', 'O', '2016-08-09', 'admin.jpg', 'T'),
('asdf', 'asdf', 'asdf', 'asdf123', 'asdf@mail.com', 'F', '2012-02-12', 'asdf.jpg', 'F'),
('Cesar', 'Azpilicueta', 'Azpilicueta', 'eden10', 'cesarazpilicueta@chelseafc.com', 'M', '2016-08-10', 'Azpilicueta.jpg', 'T'),
('asdf', 'asdf', 'qwerty', 'asdf123', 'uidawhuidwhuidw@gmail.com', 'F', '2016-08-16', 'qwerty.jpg', 'F'),
('Steven', 'Gerrard', 'stevieg', 'stevieg8', 'stevieg@gmail.com', 'M', '2012-02-12', 'stevieg.jpg', 'T'),
('Junhong', 'Wee', 'whoisjunhong', 'asdf123', 'weejunhong@gmail.com', 'M', '2016-08-04', 'whoisjunhong.jpg', 'F');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
